MODEL:
  arch: 'resnet18' # ('resnet18', 'wideres', 'wrn_s2m2')

DATA:
  dataset: 'cub'
  batch_size_loader: 256
  enlarge: True
  num_workers: 4
  disable_random_resize: False
  jitter: False
  path: 'data'

EVAL:
  evaluate: True      # Set to True to evaluate methods
  number_tasks: 1000 # Number of tasks to evaluate
  batch_size: 1000
  n_ways: 5
  n_query: 15 # Balanced case: 15 query data per class
  balanced: 'balanced' # ('balanced' | 'dirichlet')
  alpha_dirichlet: 2
  model_tag: 'best'
  plt_metrics: ['accs']
  shots: [1,3,5]
  used_set: 'test'
  fresh_start: False
