

MODEL:
   arch: 'WRN' # ('resnet18', 'wideres')
   num_classes: 64



DATA:
    dataset: 'mini'
    dataset_path: 'data/mini_imagenet'
    batch_size_loader: 256
    enlarge: True
    num_workers: 4
    disable_random_resize: False
    jitter: False
    path: 'data'
    split_dir: 'split/mini'
    target_data_path:
    target_split_dir:

EVAL:
    evaluate: True      # Set to True to evaluate methods
    number_tasks: 1000 # Number of tasks to evaluate
    batch_size: 1000
    n_ways: 5
    n_query: 15 # Balanced case: 15 query data per class
    balanced: 'balanced' # ('balanced' | 'dirichlet')
    alpha_dirichlet: 2
    model_tag: 'best'
    plt_metrics: ['accs']
    shots: [1,3,5]
    used_set: 'test'
    fresh_start: False

DISTRIBUTED:
    cuda: True
    visdom_port:
    seed: 2020
    ckpt_path: 'checkpoints/mini/softmax/wideres' # path model checkpoint
    log_path: 'logs' # path to where log files will be saved 